=== LokiMidgard/Resistance/Content/Configuration/ConfigurationSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ConfigurationSchema"
    targetNamespace="http://resistance.res"
    elementFormDefault="qualified"
    xmlns="http://resistance.res"
    xmlns:mstns="http://resistance.res"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="World" type="World"/>
        <xs:element name ="Player" type="Player"/>
        <xs:element name ="Human" type="Human"/>
        <xs:element name ="EnemyPredator" type ="EnemyPredator"/>
        <xs:element name ="EnemyCollector" type="Enemy"/>
        <xs:element name ="EnemyMine" type="Enemy"/>
        <xs:element name ="EnemyDestroyer" type="EnemyDestroyer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="World">
    <xs:sequence>
      <xs:element name ="EnemyShotSpeed" type="xs:float" minOccurs ="1" maxOccurs ="1"/>
    </xs:sequence>
    <xs:attribute name ="width" type ="xs:int" use="required"/>
    <xs:attribute name ="height" type ="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name ="Human">
    <xs:attribute name="numberFirstLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="raisePerLevelMin" type ="xs:int" use ="required"/>
    <xs:attribute name="raisePerLevelMax" type ="xs:int" use ="required"/>
  </xs:complexType>
  <xs:complexType name ="Player">
    <xs:sequence>
      <xs:element   name="MaxLifePoints"  type="xs:int" minOccurs="1" maxOccurs="1"/>
      <xs:element   name="Speed" type="xs:float" minOccurs="1" maxOccurs="1"/>
      <xs:element   name="ShootSpeed" type="xs:float" minOccurs="1" maxOccurs="1"/>
      <xs:element   name="ShootCount" type="xs:int" minOccurs="1" maxOccurs="1"/>
      <xs:element   name="MaxBombSize" minOccurs="1" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="X" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Y" type="xs:int" minOccurs="1" maxOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element   name="TimeToMaxDetonation"  type="xs:float" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name ="Enemy">
    <xs:sequence>
      <xs:element name="Speed" type="xs:int"/>
    </xs:sequence>
    <xs:attribute name="numberFirstLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="appearsInLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="minAditionalPerLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="maxAditionalPerLevel" type ="xs:int" use ="required"/>
  </xs:complexType>
  <xs:complexType name ="EnemyDestroyer">
    <xs:sequence>
      <xs:element name="Speed" type="xs:int"/>
      <xs:element name="DamageCapathyty" type="xs:int"/>      
    </xs:sequence>
    <xs:attribute name="appearsInLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="probabilityPerSeccond" type ="xs:float" use ="required"/>
    <xs:attribute name="raiseProbabilityPerLevel" type ="xs:float" use ="required"/>
    <xs:attribute name="minTimeBetweenAppereance" type ="xs:double" use ="required"/>
  </xs:complexType>
  <xs:complexType name ="EnemyPredator">
    <xs:sequence>
      <xs:element name="Speed" type="xs:int"/>
      <xs:element name="Targeting" type="xs:boolean"/>
    </xs:sequence>
    <xs:attribute name="numberFirstLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="appearsInLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="minAditionalPerLevel" type ="xs:int" use ="required"/>
    <xs:attribute name="maxAditionalPerLevel" type ="xs:int" use ="required"/>
  </xs:complexType>

</xs:schema>

=== LokiMidgard/Resistance/Content/Configuration/GameConfig.xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration
 xmlns="http://resistance.res"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://resistance.res ConfigurationSchema.xsd">
  <World width="4000" height="800">
    <EnemyShotSpeed>48</EnemyShotSpeed>
  </World>
  <Player>
    <MaxLifePoints>5</MaxLifePoints>
    <Speed>64</Speed>
    <ShootSpeed>84</ShootSpeed>
    <ShootCount>10</ShootCount>
    <MaxBombSize>
      <X>500</X>
      <Y>500</Y>
    </MaxBombSize>
    <TimeToMaxDetonation>2</TimeToMaxDetonation>
  </Player>
  <Human numberFirstLevel="10" raisePerLevelMax="3" raisePerLevelMin="2"/>
  <EnemyPredator numberFirstLevel="3" appearsInLevel="2" minAditionalPerLevel="3" maxAditionalPerLevel="4">
    <Speed>16</Speed>
    <Targeting>false</Targeting>
  </EnemyPredator>
  <EnemyCollector numberFirstLevel="5" appearsInLevel="1" maxAditionalPerLevel="3" minAditionalPerLevel="2">
    <Speed>16</Speed>
  </EnemyCollector>
  <EnemyMine numberFirstLevel="0" appearsInLevel="3" minAditionalPerLevel="2" maxAditionalPerLevel="4">
    <Speed>82</Speed>
  </EnemyMine>
  <EnemyDestroyer appearsInLevel="4" minTimeBetweenAppereance="10" probabilityPerSeccond="0.001" raiseProbabilityPerLevel="0.001">
    <Speed>200</Speed>
    <DamageCapathyty>4</DamageCapathyty>
  </EnemyDestroyer>
</Configuration>
